export const SELECCIONAR_CLIENTE = 'SELECCIONAR_ CLIENTE';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_ PRODUCTO';
export const CANTIDAD_PRODUCTOS = 'CANTIDAD_ PRODUCTO';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';